### PR TITLE
Feature/user management

### PR DESCRIPTION
**Pull request by ivanmrsulja**
Added everything from [user management issue](https://github.com/chenejac/TeslaRIS-backend/issues/8).

Added unit tests for every functionality of said issue.
Added unit tests for every retroactive functionality.

Slight code decoupling into separate services for fetching person, organisational unit and language.

### CODE REVIEW

**Review by chenejac — APPROVED** [review]
@ivanmrsulja looks good. Validation constraints messages will be returned to client side, right? Is that going to be shown to the end user? If yes, we will need i18n of those messages. However, we can think about that a little bit later.

**Comment by chenejac** [comment]
@ivanmrsulja please resolve conflicts before we merge this branch

**Comment by ivanmrsulja** [comment]
> @ivanmrsulja looks good. Validation constraints messages will be returned to client side, right? Is that going to be shown to the end user? If yes, we will need i18n of those messages. However, we can think about that a little bit later.

Yes, for every field there will be a validation exception message if it happens, we can maybe add localization in BindException handler, or do it on client side.

**Comment by ivanmrsulja** [comment]
Merge conflict resolved 😄

**Pull request merged**
